In [21]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [9]:
import DataStore

ds = DataStore.DataStore("data", 5)

In [4]:
!ls models/experimental/

A-1.h5


In [7]:
loaded_model = tf.keras.models.load_model('models/experimental/A-1.h5')

In [8]:
loaded_model.layers

In [12]:
ds.testData['A-1'].x[0]

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 1., 0., 0.]])

In [31]:
preds = loaded_model.predict(ds.testData['A-1'].x)

In [15]:
preds.shape

(8634, 1, 25)

In [17]:
ds.testData['A-1'].y.shape

(8634, 25)

In [18]:
ds.testData['A-1'].y[0]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
preds[0]

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [20]:
from Utils import get_dynamic_threshold


get_dynamic_threshold(ds.testData['A-1'].y[0], preds[0])

0.14146055246327063

In [36]:
tst = np.abs(ds.testData['A-1'].y[0] - preds[0])

In [39]:
tst > .14146

array([[False, False, False, False, False,  True,  True, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False]])